name: eis_toolkit
channels:
  - conda-forge
dependencies:
  - python >=3.9.15,<3.11
  - gdal >=3.0.2,<4.0.0
  - pip:
      - rasterio >=1.3.0
      - pandas >=2.0.0
      - geopandas  >=0.11.1
      - scikit-learn  >=1.1.2
      - matplotlib >=3.5.3
      - statsmodels >=0.14.0
      - keras >=2.9.0,<3.0.0
      - tensorflow >=2.9.1
      - beartype >=0.13.1
      - seaborn >=0.13.0
      - pykrige >=1.7.0
      - rtree >=1.0.1
      - typer[all] >=0.9.0
      - imbalanced-learn >=0.11.0
      - pysal >=23.7
      - esda >=2.5.1
      - pytest
