name: Conda

on:
  pull_request:
  push:
jobs:
  pip:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        platform: ["windows-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "1.5.6-0" # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment-pip.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: "all"
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Print pip environment
        run: |
          micromamba run -n eis_toolkit python${{ matrix.python-version }} --version
          micromamba run -n eis_toolkit python${{ matrix.python-version }} -m pip list

      - name: Run unit tests
        run: |
          # Test package import
          micromamba run -n eis_toolkit python${{ matrix.python-version }} -c 'import eis_toolkit'
          # Run unittests with pytest
          micromamba run -n eis_toolkit python${{ matrix.python-version }} -m pytest -v
